grafana:
  container_name: grafana
  image: 
    grafana/grafana
  ports:
    - "3000:3000"
  links:
    - influxdb
  volumes:
    - ./grafana/etc/grafana:/etc/grafana
    - ./grafana/var/lib/grafana:/var/lib/grafana
    
influxdb:
  container_name: influxdb
  image:
    tutum/influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
  env_file:
    - 'env.influxdb'